# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['birthday']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['published_date']},
        ),
        migrations.AddField(
            model_name='child',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='default', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/nothing.jpg', upload_to='event_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='default', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='first_name',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='slug',
            field=models.SlugField(default='default', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='image',
            field=models.ImageField(default='children_images/smiley.jpg', upload_to='children_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default='gallery_images/nothing.jpg', upload_to='gallery_images/%Y/%m/%d/%H_%M_%S'),
        ),
    ]
