# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 22:58
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170317_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['birthday'], 'verbose_name_plural': 'children'},
        ),
        migrations.AlterField(
            model_name='child',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='children_images/smiley.jpg', upload_to='children_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='event_images/nothing.jpg', upload_to='event_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='gallery_images/nothing.jpg', upload_to='gallery_images/%Y/%m/%d/%H_%M_%S'),
        ),
    ]
