# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CareCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tagline', models.CharField(max_length=256)),
                ('english_description', models.TextField(max_length=2000)),
                ('french_description', models.TextField(max_length=2000)),
                ('image', models.ImageField(default='carecentre/nothing.jpg', upload_to='carecentre_images/%Y/%m/%d/%H_%M_%S')),
                ('age_groups', models.CharField(max_length=255)),
                ('rates', models.TextField(max_length=500)),
                ('openings', models.BooleanField(default=True)),
                ('features', models.TextField(blank=True, max_length=500, null=True)),
                ('hours_of_operation', models.TextField(max_length=500)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('province_or_state', models.CharField(blank=True, max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('lattitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('administrators', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='children_images/smiley.jpg', upload_to='children_images/%Y/%m/%d/%H_%M_%S')),
                ('join_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('carecentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carecentres.CareCentre')),
            ],
            options={
                'verbose_name_plural': 'children',
                'ordering': ['birthday'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField(verbose_name='event date')),
                ('theme', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(default='event_images/nothing.jpg', upload_to='event_images/%Y/%m/%d/%H_%M_%S')),
                ('published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('carecentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carecentres.CareCentre')),
            ],
            options={
                'verbose_name_plural': 'events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='gallery_images/nothing.jpg', upload_to='gallery_images/%Y/%m/%d/%H_%M_%S')),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('published', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carecentres.Event')),
            ],
            options={
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('carecentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carecentres.CareCentre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carecentres.Parent'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carecentres.Parent'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='carecentre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carecentres.CareCentre'),
        ),
    ]
