# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carecentres', '0004_auto_20170724_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='allergies',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
